#!/usr/bin/env python

import rospy

from comp0037_explorer.explorer_WaveFront import ExplorerNodeWFD

if __name__ == '__main__':
    try:
        explorerNode = ExplorerNodeWFD()
        explorerNode.run()
    except rospy.ROSInterruptException:
        pass
